### ISSUE TITLE
default erb tag 

### ISSUE THREAD

**Issue by scottbarrow** [joseramonc/rails-snippets#20]
(cmd+shift+.) - default erb tag now seems to produce <% %> 
it used to produce <%= %>

when you rely on keybinding working the same way you tend not to look at it, after the latest update the functionality has changed, which can trip up users.

**Comment by joseramonc** [comment]
Do you have the default overwritten? I'm not having this issue, my first erb tag is still `<%= %>`. Can you help me debug and fix this?

**Comment by scottbarrow** [comment]
no defaults afaik. I even debugged it and can see the `ERB_BLOCKS[0] => <%= %>`
the const has ERB_BLOCKS = `[['<%=', '%>'], ['<%', '%>'], ['<%#', '%>']];`
It used to use the output tag but change since the update.

**Comment by scottbarrow** [comment]
I just uninstalled and reinstalled the plug and I'm not getting comment tags as default `<%#  %>`

**Comment by scottbarrow** [comment]
ha I reinstalled it once more and now the <%= %> tag is back as default :shurg:

**Comment by joseramonc** [comment]
It does the same behavior when disabling and enabling the package. It only get fixed by reloading atom. It moves the index of the default block by 1. My guess is that some iteration on this package is persisting or something like that.

I don't know when I'm going to be able to debug this but if anyone wants to try to fix it I'd be more than happy to merge it.

**Comment by scottbarrow** [comment]
had this reoccur again today after an update

**Comment by joseramonc** [comment]
Closing this because the default behavior is to reload the editor when installing packages.
