### ISSUE TITLE
Snippet shorcut keys doesn't work

### ISSUE THREAD

**Issue by peyloride** [joseramonc/rails-snippets#24]
I can use snippets via alt+shift+s menu but i can't get it work by just pressing ctrl+shift+. I'm using Turkish Q Keyboard Layout maybe something related to  this?

Thanks.

**Comment by joseramonc** [comment]
The [keybindings](https://github.com/joseramonc/rails-snippets/blob/master/keymaps/rails-snippets.cson) are `ctrl->` and `cmd->`.

The problem is that american keyboard has mapped `shift-.` to get `>`. That's why the readme says `ctrl-shift-.`. Maybe turkish keyboard has mapped `>` symbol in different keys but try pushing `ctrl->`.

If above doesn't work you can override your keybindings if you want to use it with `ctrl-.` or whatever youre used to with
```
'atom-text-editor:not(.mini)':
  'ctrl->': 'rails-snippets:toggleErb'
```

**Comment by peyloride** [comment]
Thanks for your reply.

My thought was correct and it was related to Turkish Keyboard problem. The real problem is, when typing   on my keyboard pressing "dot" button gives me a dot, it's correct. But when i try to execute shortcuts with my "dot" key atom thinks it is "/" key. So when typing atom uses native keyboard keymap but when it comes to shortcuts, its executing via american keymap. It was really hard to figure it out. But thanks anyway. And really thank you for this package, it makes my life happier.
