### ISSUE TITLE
`.each` is missing from embedded ruby files

### ISSUE THREAD

**Issue by TopOneOfTopOne** [joseramonc/rails-snippets#26]
`.each` trigger does not show up in erb files however it works in rb files even though it is an "embedded each".
Also if you have something like this `@project.` you will get a list of triggers beginning with `.` however if you type something afterwards `@project.f` all the `.` triggers disappear even the matching ones.

so.. what is going on?
Thanks :)

**Comment by joseramonc** [comment]
First of all, thanks for reporting and caring for this package, appreciate it 👍 

The `.each` works in `erb` and `rb` because there is an `.each` [snippet](https://github.com/joseramonc/rails-snippets/blob/master/snippets/views_embeded_ruby.cson#L9) for `erb` files and [one](https://github.com/joseramonc/rails-snippets/blob/master/snippets/ruby_files.cson#L82) for `.rb`files.

Second part is related to #22 and alredy reported [here](https://github.com/atom/autocomplete-snippets/issues/67). This could be fixed by changing snippets starting with `.`. However I think those snippets shouldn't be prompted everywhere, I hope `dot snippets` get officially supported soon. In the meantime I don't think it's worth to change them until they are officially not supported.

I hope this helps you.

**Comment by TopOneOfTopOne** [comment]
Thank you for the reply. After turning autocompletion off it still did not fix `.each` trigger.

After some investigation it turns out all the multiline snippets in `views_embedded_ruby.cson` do not work. However if you move the code over to `views.cson` the multiline snippets work. Also you are missing `%>` for those multiline snippets [here](https://github.com/joseramonc/rails-snippets/blob/master/snippets/views_embeded_ruby.cson#L9)

**Comment by joseramonc** [comment]
`views_embedded_ruby.cson` work in erb files and cursor is in an erb block like this: 
![screen shot 2016-05-31 at 1 36 42 pm](https://cloud.githubusercontent.com/assets/1993929/15686273/247954a6-2735-11e6-8aa9-c909dd0f2b43.png)

(I did it like this because I usually start writing variables inside erb blocks and then I remember that need to iterate on them, so `.each` snippet meets my expectatives completing my loop while retaining the current erb block.)

There's a `=loop` for html [here](https://github.com/joseramonc/rails-snippets/blob/master/snippets/views.cson#L11) if you think those snippets can be improved feel free to propose changes 😄
