### ISSUE TITLE
belongs_to worse than default Atom snippet

### ISSUE THREAD

**Issue by Albertc** [joseramonc/rails-snippets#28]
With rails-snippets package:
`belongs_to` **generate** `belongs_to :product, dependent: :destroy`

With default Atom Ruby package
`belongs_to` **generate** `belongs_to :object, :class_name => "", :foreign_key => "reference_id"`

I think _rails-snippets_ should leave ruby snippets to default Atom package, and act only for html.erb snippets

**Comment by joseramonc** [comment]
I like the way this package simplifies that snippet, the goal of this package is to use better defaults for rails snippets and generate more code according to rails conventions. That is guessing the foreign key, class, etc.

I'd like to help you but I'm happy with the first snippet, I guess we would have to ask atom for a way to enable/disable some snippets in a package in order to cover your use case.
